spring:
  profiles:
    active: default

server:
  port: 80

---

spring:
  application:
    name: spring-cloud-gateway-demo
  config:
    import: "configserver:"
    activate:
      on-profile:
        - default
  cloud:
    config:
      uri: http://localhost:10081
      name: spring-cloud-gateway-demo
      profile: dev
      fail-fast: true
      retry:
        max-attempts: 10
    gateway:
      default-filters:
        - StripPrefix=1

---

server:
  port: 80

spring:
  application:
    name: spring-cloud-gateway-demo
  config:
    activate:
      on-profile:
        - standalone
  cloud:
    config:
      enabled: false
      uri: http://localhost:10081
      name: spring-cloud-gateway-demo
      profile: dev
      fail-fast: true
      retry:
        max-attempts: 10
    gateway:
      default-filters:
        - name: GlobalLoggingFilter
          args:
            base-message: GlobalLoggingFilter Message
            preLogger: true
            postLogger: true
        - StripPrefix=1
      routes:
        - id: spring-webflux-demo
          uri: lb://webflux-demo
          predicates:
            - "Path=/webflux-demo/**"
          filters:
            - AddRequestHeader=webflux-demo, webflux-demo-request-header
            - AddResponseHeader=webflux-demo, webflux-demo-response-header
            - LoggingFilter
        - id: spring-webflux-demo2
          uri: http://192.168.1.100:30080
          predicates:
            - "Path=/webflux-demo2/**"
          filters:
            - AddRequestHeader=webflux-demo, webflux-demo2-request-header
            - AddResponseHeader=webflux-demo, webflux-demo2-response-header
    discovery:
      client:
        simple:
          instances:
            webflux-demo:
              - uri: http://192.168.1.100:30080
              - uri: http://192.168.1.100:30081
