spring:
  profiles:
    active: default

server:
  port: 80

---

spring:
  application:
    name: spring-cloud-gateway-demo
  config:
    import: "configserver:"
    activate:
      on-profile:
        - default
  cloud:
    config:
      uri: http://localhost:10081
      name: spring-cloud-gateway-demo
      profile: dev
      fail-fast: true
      retry:
        max-attempts: 10
    gateway:
      default-filters:
        - StripPrefix=1

---

server:
  port: 80

spring:
  application:
    name: spring-cloud-gateway-demo
  config:
    activate:
      on-profile:
        - standalone
  cloud:
    config:
      enabled: false
      uri: http://localhost:10081
      name: spring-cloud-gateway-demo
      profile: dev
      fail-fast: true
      retry:
        max-attempts: 10
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: false
    gateway:
      default-filters:
        - name: GlobalLoggingFilter
          args:
            base-message: GlobalLoggingFilter Message
            preLogger: true
            postLogger: true
        - name: CircuitBreaker
          args:
            fallbackUri: forward:/strip/fallback
        - StripPrefix=1
      routes:
        - id: fallbackUri
          uri: lb://webflux-demo
          predicates:
            - "Path=/strip/fallback/**"
        - id: spring-webflux-demo
          uri: lb://webflux-demo
          predicates:
            - "Path=/webflux-demo/**"
          filters:
            - AddRequestHeader=webflux-demo, webflux-demo-request-header
            - AddResponseHeader=webflux-demo, webflux-demo-response-header
            - LoggingFilter
        - id: spring-webflux-demo-nolb
          uri: http://localhost:30080
          predicates:
            - "Path=/webflux-demo-nolb/**"
          filters:
            - AddRequestHeader=webflux-demo, webflux-demo2-request-header
            - AddResponseHeader=webflux-demo, webflux-demo2-response-header
        - id: spring-webflux-demo-fallback
          uri: http://localhost:30082
          predicates:
            - "Path=/webflux-demo-fallback/**"
          filters:
            - name: CircuitBreaker
              args:
                fallbackUri: forward:/strip/fallback
        - id: spring-webflux-demo-circuitbreaker
          uri: lb://webflux-demo
          predicates:
            - "Path=/webflux-demo-circuitbreaker/**"
          filters:
            - name: CircuitBreaker
              args:
                name: webflux-demo
                fallbackUri: forward:/strip/fallback
    discovery:
      client:
        simple:
          instances:
            webflux-demo:
              - uri: http://localhost:30080
              - uri: http://localhost:30081

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: false
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 50
        waitDurationInOpenState: 2s
      someShared:
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 10
    instances:
      webflux-demo:
        baseConfig: default
        failureRateThreshold: 20
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      webflux-demo:
        baseConfig: default
        timeoutDuration: 2s
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
    instances:
      webflux-demo:
        baseConfig: default
